version: '3.5'

services:
  cms-ui-dev:
    container_name: cms-ui-dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3002'
    environment:
      - NODE_ENV=development
